version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend-app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: frontend-app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
