#!/bin/sh

echo "==> Running ktlint in 05-react-06-tests/backend..."

cd 05-react-06-tests/backend || {
  echo "❌ Could not change directory to 05-react-06-tests/backend. Aborting commit."
  exit 1
}

./gradlew ktlintCheck
if [ $? -ne 0 ]; then
  echo "❌ ktlintCheck failed. Fix formatting issues before committing."
  exit 1
fi

echo "✅ ktlintCheck passed."

echo "==> Running frontend checks (lint-staged + tests)..."

cd ../../05-react-06-tests//frontend || {
  echo "❌ Could not change directory to 05-react-06-tests//frontend. Aborting commit."
  exit 1
}

echo "⚡ Running lint-staged..."
npx eslint 'src/**/*.{js,jsx}' 
if [ $? -ne 0 ]; then
  echo "❌ Linting failed. Please fix the issues before committing."
  exit 1
fi

echo "✅ Linting passed."
